### ISSUE TITLE
Setting number of workers above 0 cause validation process to freeze when using python scripts on Baskerville

### ISSUE THREAD

**Issue by evangeline-corcoran** [alan-turing-institute/cloudcasting#67]
When trying to run validation for a model using a python script, if I set `num_workers = 0` it runs without issues, but if `num_workers` is greater than zero the run freezes and produces the following error message:

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/bask/projects/v/vjgo8416-climate/of_cloud/lib/python3.12/multiprocessing/spawn.py", line 122, in spawn_main
    exitcode = _main(fd, parent_sentinel)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/bask/projects/v/vjgo8416-climate/of_cloud/lib/python3.12/multiprocessing/spawn.py", line 131, in _main
    prepare(preparation_data)
  File "/bask/projects/v/vjgo8416-climate/of_cloud/lib/python3.12/multiprocessing/spawn.py", line 246, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "/bask/projects/v/vjgo8416-climate/of_cloud/lib/python3.12/multiprocessing/spawn.py", line 297, in _fixup_main_from_path
    main_content = runpy.run_path(main_path,
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen runpy>", line 286, in run_path
  File "<frozen runpy>", line 98, in _run_module_code
  File "<frozen runpy>", line 88, in _run_code
  File "/bask/projects/v/vjgo8416-climate/users/lwcf1795/optical_flow/tvl1/of-tvl1-model-eval.py", line 158, in <module>
    validate(
  File "/bask/projects/v/vjgo8416-climate/of_cloud/lib/python3.12/site-packages/jaxtyping/_decorator.py", line 522, in wrapped_fn
    return wrapped_fn_impl(args, kwargs, bound, memos)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/bask/projects/v/vjgo8416-climate/of_cloud/lib/python3.12/site-packages/jaxtyping/_decorator.py", line 449, in wrapped_fn_impl
    out = fn(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^
  File "/bask/homes/l/lwcf1795/cloudcasting/src/cloudcasting/validation.py", line 350, in validate
    channel_horizon_metrics_dict, channel_names = score_model_on_all_metrics(
                                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/bask/projects/v/vjgo8416-climate/of_cloud/lib/python3.12/site-packages/jaxtyping/_decorator.py", line 522, in wrapped_fn
    return wrapped_fn_impl(args, kwargs, bound, memos)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/bask/projects/v/vjgo8416-climate/of_cloud/lib/python3.12/site-packages/jaxtyping/_decorator.py", line 449, in wrapped_fn_impl
    out = fn(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^
  File "/bask/homes/l/lwcf1795/cloudcasting/src/cloudcasting/validation.py", line 235, in score_model_on_all_metrics
    for i, (X, y) in tqdm(enumerate(valid_dataloader), total=loop_steps):
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/bask/projects/v/vjgo8416-climate/of_cloud/lib/python3.12/site-packages/torch/utils/data/dataloader.py", line 440, in __iter__
    return self._get_iterator()
           ^^^^^^^^^^^^^^^^^^^^
  File "/bask/projects/v/vjgo8416-climate/of_cloud/lib/python3.12/site-packages/torch/utils/data/dataloader.py", line 388, in _get_iterator
    return _MultiProcessingDataLoaderIter(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/bask/projects/v/vjgo8416-climate/of_cloud/lib/python3.12/site-packages/torch/utils/data/dataloader.py", line 1038, in __init__
    w.start()
  File "/bask/projects/v/vjgo8416-climate/of_cloud/lib/python3.12/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
                  ^^^^^^^^^^^^^^^^^
  File "/bask/projects/v/vjgo8416-climate/of_cloud/lib/python3.12/multiprocessing/context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/bask/projects/v/vjgo8416-climate/of_cloud/lib/python3.12/multiprocessing/context.py", line 289, in _Popen
    return Popen(process_obj)
           ^^^^^^^^^^^^^^^^^^
  File "/bask/projects/v/vjgo8416-climate/of_cloud/lib/python3.12/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/bask/projects/v/vjgo8416-climate/of_cloud/lib/python3.12/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/bask/projects/v/vjgo8416-climate/of_cloud/lib/python3.12/multiprocessing/popen_spawn_posix.py", line 42, in _launch
    prep_data = spawn.get_preparation_data(process_obj._name)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/bask/projects/v/vjgo8416-climate/of_cloud/lib/python3.12/multiprocessing/spawn.py", line 164, in get_preparation_data
    _check_not_importing_main()
  File "/bask/projects/v/vjgo8416-climate/of_cloud/lib/python3.12/multiprocessing/spawn.py", line 140, in _check_not_importing_main
    raise RuntimeError('''
RuntimeError: 
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.

        To fix this issue, refer to the "Safe importing of main module"
        section in https://docs.python.org/3/library/multiprocessing.html

```
If I use the same code within a jupyter notebook, I can run validation with a higher number of workers without issue.

**Comment by evangeline-corcoran** [comment]
resolved by editing my python script to call `validate(..)` within a ` __name__=="__main__" ` block. i.e:
```
if __name__=="__main__":
    validate(..)
```
